"""add_current_to_account_type_enum

Revision ID: 0e85cbb40c66
Revises: 5cc85e390b25
Create Date: 2025-09-23 23:25:46.877554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e85cbb40c66'
down_revision: Union[str, Sequence[str], None] = '5cc85e390b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing values to accounttype enum (only CURRENT is missing)
    op.execute("ALTER TYPE accounttype ADD VALUE 'CURRENT'")
    # SALARY and JOINT already exist in the database
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values, so downgrade is not possible
    pass
    # ### end Alembic commands ###
