"""update_education_level_and_occupation_sector_enums

Revision ID: 5cc85e390b25
Revises: c7566ccd73cd
Create Date: 2025-09-23 23:22:41.171052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cc85e390b25'
down_revision: Union[str, Sequence[str], None] = 'c7566ccd73cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new values to educationlevel enum (only missing ones)
    op.execute("ALTER TYPE educationlevel ADD VALUE 'BACHELORS'")
    op.execute("ALTER TYPE educationlevel ADD VALUE 'MASTERS'")
    op.execute("ALTER TYPE educationlevel ADD VALUE 'PHD'")

    # Add new values to occupationsector enum (only missing ones)
    op.execute("ALTER TYPE occupationsector ADD VALUE 'IT'")
    op.execute("ALTER TYPE occupationsector ADD VALUE 'FINANCE'")
    op.execute("ALTER TYPE occupationsector ADD VALUE 'HEALTHCARE'")
    op.execute("ALTER TYPE occupationsector ADD VALUE 'EDUCATION'")
    op.execute("ALTER TYPE occupationsector ADD VALUE 'OTHER'")
    op.alter_column('auth', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('auth', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('auth', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('auth', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('auth_username_key'), 'auth', type_='unique')
    op.create_index(op.f('ix_auth_username'), 'auth', ['username'], unique=True)
    op.create_unique_constraint(None, 'auth', ['user_id'])
    op.drop_column('auth', 'is_superuser')
    op.drop_column('auth', 'hashed_password')
    op.alter_column('customer_growth', 'new_customers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customer_growth', 'churned_customers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customer_growth', 'net_growth',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customer_recommendations', 'recommended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('customer_recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('customer_segments', 'value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('monthly_trends', 'deposits',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('monthly_trends', 'withdrawals',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('monthly_trends', 'net_flow',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('product_performance', 'current',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('product_performance', 'previous',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('product_performance', 'period',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('recommendations', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recommendations', 'segment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('recommendations', 'conversion_rate')
    op.drop_column('recommendations', 'customer_count')
    op.alter_column('regional_performance', 'customers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('regional_performance', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('regional_performance', 'growth',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('regional_performance', 'period',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'account_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('transactions_account_number_fkey'), 'transactions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Note: PostgreSQL doesn't support removing enum values directly
    # These would need to be handled manually if needed
    op.create_foreign_key(op.f('transactions_account_number_fkey'), 'transactions', 'users', ['account_number'], ['account_number'])
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'account_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('regional_performance', 'period',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('regional_performance', 'growth',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('regional_performance', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('regional_performance', 'customers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('recommendations', sa.Column('customer_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recommendations', sa.Column('conversion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('recommendations', 'segment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recommendations', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('product_performance', 'period',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product_performance', 'previous',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('product_performance', 'current',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('monthly_trends', 'net_flow',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('monthly_trends', 'withdrawals',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('monthly_trends', 'deposits',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('customers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('customer_segments', 'value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer_recommendations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('customer_recommendations', 'recommended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('customer_growth', 'net_growth',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer_growth', 'churned_customers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer_growth', 'new_customers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('auth', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('auth', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'auth', type_='unique')
    op.drop_index(op.f('ix_auth_username'), table_name='auth')
    op.create_unique_constraint(op.f('auth_username_key'), 'auth', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('auth', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('auth', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('auth', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('auth', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
