"""add_IN_to_nationality_enum

Revision ID: f62162dade03
Revises: 95054c2ada4a
Create Date: 2025-09-24 01:10:44.907403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62162dade03'
down_revision: Union[str, Sequence[str], None] = '95054c2ada4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE nationality ADD VALUE 'IN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values directly
    # This would require recreating the enum type without 'IN'
    pass
    # ### end Alembic commands ###
